name: Sync Fork with Upstream # 工作流名称，清晰表明其目的

on:
  workflow_dispatch: # 允许手动触发，以便您随时手动同步
  schedule:
    - cron: '0 19 * * *' #表示 UTC 时间每天 19:00（即北京时间次日凌晨 3:00）触发编译。

permissions:
  contents: write # 授予写入权限，以便工作流可以将变更推送到您的仓库

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: coolsnowwolf # fork 的上游仓库 user
          head: master # fork 的上游仓库 branch
          base: master # 本地仓库 branch